"""对象存储（MinIO）封装（design.md §3.1：只存取字节，不做权限判定）。"""

from app.engines.storage.object_store import (
    ASSETS_DIR,
    MAX_NAME_LENGTH,
    MEDIA_TYPES,
    PARSED_DIR,
    SOURCE_DIR,
    UNIT_PREFIX,
    ObjectStoreError,
    asset_key,
    assets_prefix,
    delete,
    delete_prefix,
    delete_unit_prefix,
    ensure_bucket,
    exists,
    get_bytes,
    get_client,
    list_keys,
    media_type_for,
    parsed_key,
    put_bytes,
    safe_name,
    source_key,
    unit_prefix,
)

__all__ = [
    "ASSETS_DIR",
    "MAX_NAME_LENGTH",
    "MEDIA_TYPES",
    "PARSED_DIR",
    "SOURCE_DIR",
    "UNIT_PREFIX",
    "ObjectStoreError",
    "asset_key",
    "assets_prefix",
    "delete",
    "delete_prefix",
    "delete_unit_prefix",
    "ensure_bucket",
    "exists",
    "get_bytes",
    "get_client",
    "list_keys",
    "media_type_for",
    "parsed_key",
    "put_bytes",
    "safe_name",
    "source_key",
    "unit_prefix",
]
