"""init_schema

Revision ID: e745c0612b4f
Revises: 
Create Date: 2026-09-14 20:22:12.022059
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e745c0612b4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_departments_parent_id', 'departments', ['parent_id'], unique=False)
    op.create_table('model_configs',
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('chat_model', sa.String(length=128), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('rerank_model', sa.String(length=128), nullable=False),
    sa.Column('faq_sim_threshold', sa.Float(), nullable=False),
    sa.Column('gap_sim_threshold', sa.Float(), nullable=False),
    sa.Column('faq_cluster_min_freq', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_department_id', 'users', ['department_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_table('faq_candidates',
    sa.Column('representative_question', sa.String(length=512), nullable=False),
    sa.Column('similar_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('freq', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('suggested_answer', sa.Text(), nullable=True),
    sa.Column('source_unit_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_faq_candidates_status_freq', 'faq_candidates', ['status', 'freq'], unique=False)
    op.create_table('knowledge_units',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('source_path', sa.String(length=512), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('acl_global', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('upload_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_units_parse_status', 'knowledge_units', ['parse_status'], unique=False)
    op.create_index('idx_knowledge_units_status', 'knowledge_units', ['status'], unique=False)
    op.create_table('qa_audit_logs',
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('rewritten', sa.Text(), nullable=True),
    sa.Column('faq_hit', sa.Boolean(), nullable=False),
    sa.Column('allowed_unit_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('denied_count', sa.Integer(), nullable=False),
    sa.Column('citation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer_status', sa.String(length=16), nullable=False),
    sa.Column('max_similarity', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qa_audit_logs_created_at', 'qa_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_qa_audit_logs_user_id', 'qa_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_qa_audit_logs_trace_id'), 'qa_audit_logs', ['trace_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_table('chunks',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_parent_id', 'chunks', ['parent_id'], unique=False)
    op.create_index('idx_chunks_unit_id_level', 'chunks', ['unit_id', 'level'], unique=False)
    op.create_table('faqs',
    sa.Column('question', sa.String(length=512), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('cache_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_candidate_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['faq_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_faqs_status', 'faqs', ['status'], unique=False)
    op.create_table('ingest_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ingest_tasks_unit_id', 'ingest_tasks', ['unit_id'], unique=False)
    op.create_table('knowledge_gaps',
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('freq', sa.Integer(), nullable=False),
    sa.Column('max_similarity', sa.Float(), nullable=True),
    sa.Column('last_asked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('filled_unit_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['filled_unit_id'], ['knowledge_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_gaps_status_freq', 'knowledge_gaps', ['status', 'freq'], unique=False)
    op.create_table('knowledge_unit_acl',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('principal_type', sa.String(length=16), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['knowledge_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'principal_type', 'principal_id', name='uq_knowledge_unit_acl_triple')
    )
    op.create_index('idx_knowledge_unit_acl_unit_id', 'knowledge_unit_acl', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_knowledge_unit_acl_unit_id', table_name='knowledge_unit_acl')
    op.drop_table('knowledge_unit_acl')
    op.drop_index('idx_knowledge_gaps_status_freq', table_name='knowledge_gaps')
    op.drop_table('knowledge_gaps')
    op.drop_index('idx_ingest_tasks_unit_id', table_name='ingest_tasks')
    op.drop_table('ingest_tasks')
    op.drop_index('idx_faqs_status', table_name='faqs')
    op.drop_table('faqs')
    op.drop_index('idx_chunks_unit_id_level', table_name='chunks')
    op.drop_index('idx_chunks_parent_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_chat_messages_session_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_qa_audit_logs_trace_id'), table_name='qa_audit_logs')
    op.drop_index('idx_qa_audit_logs_user_id', table_name='qa_audit_logs')
    op.drop_index('idx_qa_audit_logs_created_at', table_name='qa_audit_logs')
    op.drop_table('qa_audit_logs')
    op.drop_index('idx_knowledge_units_status', table_name='knowledge_units')
    op.drop_index('idx_knowledge_units_parse_status', table_name='knowledge_units')
    op.drop_table('knowledge_units')
    op.drop_index('idx_faq_candidates_status_freq', table_name='faq_candidates')
    op.drop_table('faq_candidates')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('idx_users_department_id', table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('model_configs')
    op.drop_index('idx_departments_parent_id', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
